"""Update post table

Revision ID: 64fec4b7d554
Revises: 788ee27c0271
Create Date: 2025-08-23 10:38:49.566708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fec4b7d554'
down_revision: Union[str, Sequence[str], None] = '788ee27c0271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('category', sa.String(), nullable=False))
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posts', 'category')
    op.drop_column('posts', 'priority')
    # ### end Alembic commands ###
